name: Postgres.app
description: "Postgres.app is a full featured PostgreSQL installation packaged as a standard Mac app."

gems: ['jekyll-github-metadata']
repository: postgresapp/postgresapp

downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/v2.1.1/Postgres-2.1.1.dmg"
releaseNotesLocation: "https://github.com/PostgresApp/PostgresApp/releases/v2.1.1/"
postgresappVersion: "2.1.1"
postgresappMinSystemVersion: "10.10"
postgresqlVersions: [
	{ postgres: "10.1", postgis: "2.4.1" },
	{ postgres: "9.6.6", postgis: "2.3.4" },
	{ postgres: "9.5.10", postgis: "2.2.6" },
]

legacyMinSystemVersion: "10.7"
legacyVersions: [
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/9.3.20/Postgres-9.3.20.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/9.3.20/",
		postgresqlVersion: "9.3.20",
		postgisVersion: "2.1.9",
	},
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/9.4.15/Postgres-9.4.15.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/9.4.15/",
		postgresqlVersion: "9.4.15",
		postgisVersion: "2.1.9",
	},
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/9.5.10/Postgres-9.5.10.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/9.5.10/",
		postgresqlVersion: "9.5.10",
		postgisVersion: "2.2.6",
	},
	{
		downloadLocation: "https://github.com/PostgresApp/PostgresApp/releases/download/9.6.6/Postgres-9.6.6.zip",
		releaseNotes: "https://github.com/PostgresApp/PostgresApp/releases/9.6.6/",
		postgresqlVersion: "9.6.6",
		postgisVersion: "2.3.4",
	},
]

languages: [en, de]

strings: {
	de: {
		subtitle: Der schnellste Weg zu PostgreSQL am Mac,
		download-button: Download,
		docs-button: Dokumentation,
		github-button: Github,
		stars: Sterne,
		follow: Folge,
		find-us: Finde uns auf,
		typo: "Feler gefunden?",
		edit-page: Bearbeite diese Seite,
	},
	en: {
		subtitle: The easiest way to get started with PostgreSQL on the Mac,
		download-button: Download,
		docs-button: Documentation,
		github-button: Github,
		stars: Stars,
		follow: Follow,
		find-us: Find us on,
		typo: "Spotted a typo?",
		edit-page: edit this page,
	}
}